//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poster
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int Commentid { get; set; }
        public string CommentText { get; set; }
        public string Name { get; set; }
        public string Commentdate { get; set; }
        public Nullable<int> Parentid { get; set; }
    }
}
