//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poster
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commend
    {
        public int CommentID { get; set; }
        public string CommandText { get; set; }
        public string Username { get; set; }
        public string CommentDate { get; set; }
        public Nullable<int> ParentId { get; set; }

        public static implicit operator Commend(Commend v)
        {
            throw new NotImplementedException();
        }
    }
}
